version: '3.4'

services:
  app:
    image: kue-getting-started:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    expose:
      - '${PORT}'
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - redis
    command: "yarn start:server"

  worker:
    image: kue-getting-started:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    depends_on:
      - redis
    command: "yarn start:worker"

  redis:
    image: redis:5-alpine
